### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by jdiazram** [MrEarle/IIC3692-2021-2#1]
Hola Benjamin
Gracias por el código.
Duda, al fina luego de los resultados de las métricas, me aparece el siguiente warning:

> WARNING:root:NaN or Inf found in input tensor.
> Traceback (most recent call last):
>   File "tasks/R2R-pano/main.py", line 300, in <module>
>     main(opts)
>   File "tasks/R2R-pano/main.py", line 270, in main
>     success_rate.append(trainer.eval(epoch, val_env, tb_logger))
>   File "/content/drive/My Drive/PROYECTO_IA_2021/Matterport-2/regretful-agent/tasks/R2R-pano/trainer.py", line 255, in eval
>     self.agent.write_results()
>   File "/content/drive/My Drive/PROYECTO_IA_2021/Matterport-2/regretful-agent/tasks/R2R-pano/agents/pano_agent.py", line 37, in write_results
>     with open(self.results_path, 'w') as f:
> FileNotFoundError: [Errno 2] No such file or directory: 'tasks/R2R-pano/results/experiments__val_seen_epoch_1.json'

Sabes que puede ser? faltará algún permiso para crear los archivos de results?
Atento a tus comentarios

Gracias

**Comment by MrEarle** [comment]
Que pasa si creas manualmente la carpeta `results` en `tasks/R2R-pano`?

Tengo la impresión que está tratando de crear un archivo ahí, pero no encuentra la carpeta.

**Comment by MrEarle** [comment]
Tambien quiero comentar que el `WARNING:root:NaN or Inf found in input tensor.` no viene de este error al escribir el archvo. Ese warning aparece cuando se generan `NaN` o `Infinito` en algún tensor. Eso ya depende de la implementación de los autores.

**Comment by jdiazram** [comment]
Efectivamente, al crear de manera manual la carpeta results en R2R-pano funciona...gracias!
Usar GPU!! es mucho más rápido!
