### ISSUE TITLE
Instalación Repositorio MG-AuxRN

### ISSUE THREAD

**Issue by BenjaPrograma** [MrEarle/IIC3692-2021-2#3]
Hola! Estoy teniendo problemas para instalar el repositorio de https://github.com/ZhuFengdaaa/MG-AuxRN
que es sobre el que quiero trabajar para mi proyecto. Pero tengo problemas para seguir la instalación.

Como no tiene los archivos base de matterport3d lo que hice fue copiar los archivos del base y luego pegar los archivos originales del repositorio mg-auxrn. Después de instalar todo, trato de correr el r2r_src/train.py pero me dice que no hay ningun modulo llamado polyaxon_client,
```
Traceback (most recent call last):
  File "r2r_src/train.py", line 20, in <module>
    from speaker import Speaker
  File "/content/drive/My Drive/Proyecto-TopicosIA/proyecto-IA/r2r_src/speaker.py", line 5, in <module>
    import utils
  File "/content/drive/My Drive/Proyecto-TopicosIA/proyecto-IA/r2r_src/utils.py", line 26, in <module>
    from polyaxon_client.tracking import get_data_paths
ModuleNotFoundError: No module named 'polyaxon_client'
```

También me di cuenta que hay un atp.sh que corre algún comando de polyaxon pero me tira un error correrlo 

```
Polyaxonfile is not valid.
Error message: The Polyaxonfile with kind `experiment` is not a supported value..
```

Saludos!

EDIT:
!pip install -U polyaxon-client

Parece que eso era lo que me faltaba y ahora está corriendo xd.

Aprovecho de preguntar entonces, hay mucha diferencia entre correr DOSMESA_RENDERING v/s DEGL_RENDERING ? Me refiero en cuanto a rendimiento, ya que en COLAB  no pude hacer correr el DEGL

**Comment by MrEarle** [comment]
Hola!

Que bueno que pudiste correrlo!

La verdad no sé exactamente la diferencia entre usar OSMesa o EGL para renderar de forma headless. Ambos debieran ir bien, usa el que te funcione nomás.
